"""The badge row as a PUBLISHED FIGURE — re-derived from source, not from its generator.

This repository drift-guards every published figure, because the alternative has
bitten it four times: a dashboard banner that said no judged run existed while
four scorecards sat in the tree, run-2 figures surviving into run 3, an ``n=33``
that had become 32, and a README claiming there were no scorecards. A badge is
the most-read figure on the page and the least likely to be re-checked by hand,
so it is the figure most worth guarding.

**Why this file exists beside ``tests/test_generate_badges.py``.** That file is
the generator's unit test: it imports ``scripts.generate_badges``, monkeypatches
its derivations, and drives its caveat states. Necessary, but it cannot close the
loop on its own — it reads the expected separator, marker and colour constants
out of the very module it is checking, so a literal that was wrong *inside* the
generator would be confirmed by its own test.

This file closes that loop. It **never imports the generator.** Every marker,
separator and expected string below is a literal typed here; every figure is
recomputed from the artifact that produced it — ``eval/scorecards/``,
``eval/f1-report.json``, ``eval/skill-eval-workspace/iteration-3/``,
``skills/*/skill.usf.yaml``, ``scenarios/registry.yaml``, ``LICENSE``,
``NOTICE``, ``vendor/skill-judge/PROVENANCE.md`` — and compared against the text
actually committed to ``README.md``. The generator is exercised exactly once,
as a black box: ``--check`` must exit 0 on the committed state.

Two imports are not the generator and are deliberate:

* ``scripts.ship_floor.aggregate_verdict`` is *the ship gate itself*, the single
  definition of SHIP in this repository. Re-implementing its arithmetic here
  would create a second copy of a gate whose constants are frozen by ADR, which
  is worse than depending on it. Each verdict is cross-checked against the
  verdict the scorecard stores, so the gate and the artifact must agree too.
* ``validators.usf.validate_manifest_file`` is the USF validator the badge is a
  claim *about*. A hand-rolled schema check here would badge a different claim.
"""

from __future__ import annotations

import json
import re
import statistics
import subprocess
import sys
from pathlib import Path
from urllib.parse import unquote

import pytest
import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.ship_floor import aggregate_verdict  # noqa: E402
from validators.usf import validate_manifest_file  # noqa: E402

README = REPO_ROOT / "README.md"
GENERATOR = REPO_ROOT / "scripts" / "generate_badges.py"

#: Typed here, not imported. If the generator's markers move, the row it thinks
#: it maintains and the row this file reads part company, and that is a failure.
BEGIN_MARKER = "<!-- BEGIN:badges — generated by scripts/generate_badges.py; do not hand-edit -->"
END_MARKER = "<!-- END:badges -->"

#: U+00B7 MIDDLE DOT. Typed as a literal so a changed separator constant inside
#: the generator cannot quietly redefine what this file expects to find.
DOT = "·"

#: `[![alt](shields url)](link)` — the only shape a badge in this row may take.
BADGE_RE = re.compile(
    r"\[!\[(?P<alt>[^\]]*)\]\((?P<img>https://img\.shields\.io/badge/[^)\s]+)\)\]\((?P<link>[^)\s]+)\)"
)

#: shields.io reads a single `-` as its field separator and doubles a literal one.
FIELD_SPLIT = re.compile(r"(?<!-)-(?!-)")


# --------------------------------------------------------------------------- #
# Reading the committed row
# --------------------------------------------------------------------------- #


def _readme() -> str:
    return README.read_text(encoding="utf-8")


def _badge_block(text: str | None = None) -> str:
    """The committed text between the badge markers, markers excluded."""
    text = _readme() if text is None else text
    start, end = text.find(BEGIN_MARKER), text.find(END_MARKER)
    assert start != -1 and end != -1 and start < end, "README.md has lost its badge markers"
    return text[start + len(BEGIN_MARKER) : end]


class ParsedBadge:
    """One badge as committed: decoded fields, colour, alt text and link."""

    def __init__(self, match: re.Match[str]) -> None:
        path = match.group("img").rsplit("/badge/", 1)[1]
        raw = FIELD_SPLIT.split(path)
        self.fields = [unquote(f).replace("--", "-").replace("__", "_") for f in raw[:-1]]
        self.colour = raw[-1]
        self.alt = match.group("alt")
        self.link = match.group("link")

    @property
    def label(self) -> str:
        return self.fields[0] if len(self.fields) == 2 else ""

    @property
    def message(self) -> str:
        return self.fields[-1]

    def __repr__(self) -> str:  # pragma: no cover - failure output only
        return f"<badge {self.label!r} {self.message!r} #{self.colour} -> {self.link}>"


def badges() -> list[ParsedBadge]:
    parsed = [ParsedBadge(m) for m in BADGE_RE.finditer(_badge_block())]
    assert parsed, "the badge block parsed to zero badges — the row shape changed"
    return parsed


def badge(label: str) -> ParsedBadge:
    for item in badges():
        if item.label == label:
            return item
    raise AssertionError(f"the badge row has no {label!r} badge; it has {[b.label for b in badges()]}")


def _run_check(readme: Path) -> subprocess.CompletedProcess[str]:
    """The generator as a BLACK BOX. No import, no shared interpreter state."""
    return subprocess.run(
        [sys.executable, str(GENERATOR), "--check", "--readme", str(readme)],
        capture_output=True,
        text=True,
        cwd=str(REPO_ROOT),
    )


# --------------------------------------------------------------------------- #
# Independent derivations. Each reads the artifact, never a summary of it.
# --------------------------------------------------------------------------- #


def _skill_roster() -> list[str]:
    roster = sorted(p.name for p in (REPO_ROOT / "skills").iterdir() if (p / "SKILL.md").is_file())
    assert roster, "skills/ ships no SKILL.md; there is no roster to badge against"
    return roster


def _judged() -> tuple[int, int, float, int]:
    """``(shipped, roster, pooled_mean, pooled_n)`` recomputed over the scorecards."""
    roster = _skill_roster()
    shipped, judgments = 0, []
    for path in sorted((REPO_ROOT / "eval" / "scorecards").glob("*.json")):
        payload = json.loads(path.read_text(encoding="utf-8"))
        skill = str(payload["skill"])
        assert skill in roster, f"{path.name} scores {skill!r}, which ships no SKILL.md"
        verdict, why = aggregate_verdict(skill, payload.get("aggregate"))
        assert verdict == payload["verdict"], (
            f"{path.name} stores verdict {payload['verdict']!r} but the gate recomputes {verdict!r} ({why})"
        )
        shipped += verdict == "SHIP"
        judgments += [float(j) for j in payload["aggregate"]["judgments"]]
    assert judgments, "eval/scorecards/ holds no judgments; there is no pooled mean to badge"
    return shipped, len(roster), round(statistics.fmean(judgments), 1), len(judgments)


def _f1_categories() -> dict[str, list[dict]]:
    report = json.loads((REPO_ROOT / "eval" / "f1-report.json").read_text(encoding="utf-8"))
    buckets: dict[str, list[dict]] = {"pass": [], "fail": [], "declared-and-uncovered": []}
    for row in report["categories"]:
        assert row["status"] in buckets, f"{row['category']}: unrecognised status {row['status']!r}"
        buckets[row["status"]].append(row)
    return buckets


def _f1_published_score() -> float:
    """The one scenario-level F1 shared by every category that publishes one.

    The pill leads with a SCORE now, so the score is recomputed from the report
    rather than read off the pill. If those categories ever stop agreeing on a
    single number there is no single number to show, and this says so before the
    badge quietly shows one of them.
    """
    scores = {row["scenario_level"]["f1"] for row in _f1_categories()["pass"]}
    assert len(scores) == 1, (
        f"the categories that publish an F1 no longer share one score {sorted(scores)}; "
        "the badge must not show a single number as if they did"
    )
    return scores.pop()


def _panel_size() -> int:
    """How many judges ``eval/scorecards/`` records, recomputed from the scorecards.

    The pill names the panel, so the panel size is a published figure like any
    other. Every scorecard must record the SAME roster and every judge in it must
    have actually returned a judgment — otherwise "the panel" is not one thing
    and the badge cannot name it with one number.
    """
    panels, judged = set(), set()
    for path in sorted((REPO_ROOT / "eval" / "scorecards").glob("*.json")):
        payload = json.loads(path.read_text(encoding="utf-8"))
        panels.add(tuple(sorted(payload["providers"])))
        judged |= {str(j["provider"]) for j in payload["judgments"]}
    assert len(panels) == 1, f"the scorecards record more than one judge panel: {sorted(panels)}"
    roster = set(panels.pop())
    assert judged == roster, (
        f"the badge names a panel of {len(roster)}; the judges that actually returned scores are {sorted(judged)}"
    )
    return len(roster)


def _control_delta() -> tuple[float, float, float, int]:
    """``(delta, with_mean, without_mean, n)`` over the blind CONTROL arm of iteration-3 alone.

    The pill publishes the two ARMS and the alt text publishes the delta, so all
    three are recomputed here. A badge that took one arm from the control and the
    other from somewhere else would still read as a coherent pair.
    """
    payload = json.loads(
        (REPO_ROOT / "eval" / "skill-eval-workspace" / "iteration-3" / "benchmark.json").read_text(encoding="utf-8")
    )
    controls = [c for c in payload["cases"] if "-control-" in c["eval"]]
    assert controls, "iteration-3 ran no -control- case; there is no blind-control delta to badge"
    with_arm = statistics.fmean(float(c["with_skill"]["pass_rate"]) for c in controls)
    without_arm = statistics.fmean(float(c["without_skill"]["pass_rate"]) for c in controls)
    return round(with_arm - without_arm, 2), round(with_arm, 2), round(without_arm, 2), len(controls)


def _usf_conformant() -> tuple[int, int]:
    roster = _skill_roster()
    conformant = 0
    for name in roster:
        manifest = REPO_ROOT / "skills" / name / "skill.usf.yaml"
        if manifest.is_file() and validate_manifest_file(manifest).ok:
            conformant += 1
    return conformant, len(roster)


def _rubric_upstream() -> str:
    provenance = (REPO_ROOT / "vendor" / "skill-judge" / "PROVENANCE.md").read_text(encoding="utf-8")
    match = re.search(r"Upstream\s*\|\s*`([\w.-]+/[\w.-]+)`", provenance)
    assert match, "vendor/skill-judge/PROVENANCE.md records no `owner/repo` upstream to attribute"
    return match.group(1)


# --------------------------------------------------------------------------- #
# 1. The committed row is the row its sources produce
# --------------------------------------------------------------------------- #


def test_check_exits_zero_on_the_committed_state():
    result = _run_check(README)
    assert result.returncode == 0, f"README.md's badge row is out of date:\n{result.stdout}{result.stderr}"


#: (name, committed substring, replacement) — one entry per DERIVED figure in the
#: row. Every value a reader could act on has to appear here: a figure with no
#: mutation case is a figure nothing stops a maintainer from retyping.
MUTATIONS = [
    ("pooled mean", "111.3", "119.9"),
    ("ship count", "11%2F11%20SHIP", "12%2F12%20SHIP"),
    # The coverage count, the by-rule clause and the delta moved off their pills
    # into their alt text when the row was reworded. They are still derived, still
    # published and still mutable by hand, so they are still guarded here — the
    # literal moves with the figure, the case does not go away.
    ("F1 coverage", "7 of 10", "10 of 10"),
    ("F1 boundary clause", "3 publish none by rule", "0 publish none by rule"),
    ("control delta", "+0.52", "+0.90"),
    ("USF conformance", "11%2F11%20skills", "9%2F11%20skills"),
    ("scenario count", "62%20%C2%B7%20tiered", "58%20%C2%B7%20tiered"),
    ("licence id", "Apache--2.0", "MIT"),
    ("rubric upstream", _rubric_upstream().replace("-", "--").replace("/", "%2F"), "an--unrelated%2Frepository"),
    ("non-endorsement", "NOT%20an%20OWASP%20project", "An%20OWASP%20project"),
]


@pytest.mark.parametrize("name,committed,replacement", MUTATIONS, ids=[m[0] for m in MUTATIONS])
def test_a_hand_edited_badge_fails_the_check(tmp_path, name, committed, replacement):
    """The failure mode this file exists for: a figure typed by hand.

    Mutate one value, prove ``--check`` rejects it, prove regenerating restores
    exactly the committed bytes. A badge that survives this loop is unguarded.
    """
    original = _readme()
    assert committed in _badge_block(original), f"{committed!r} is no longer in the row; this case tests nothing"
    copy = tmp_path / "README.md"
    copy.write_text(original.replace(committed, replacement, 1), encoding="utf-8")

    assert _run_check(copy).returncode == 1, f"a hand-edited {name} passed --check"
    rewrite = subprocess.run(
        [sys.executable, str(GENERATOR), "--readme", str(copy)], capture_output=True, text=True, cwd=str(REPO_ROOT)
    )
    assert rewrite.returncode == 0, rewrite.stderr
    assert copy.read_text(encoding="utf-8") == original, f"regenerating did not restore the derived {name}"


def test_a_deleted_badge_fails_the_check(tmp_path):
    """Dropping a badge is drift too. The row cannot silently get shorter."""
    original = _readme()
    for target in badges():
        block = _badge_block(original)
        rendered = next(m.group(0) for m in BADGE_RE.finditer(block) if ParsedBadge(m).link == target.link)
        copy = tmp_path / "README.md"
        copy.write_text(original.replace(rendered, "", 1), encoding="utf-8")
        assert _run_check(copy).returncode == 1, f"deleting the {target.label or target.message!r} badge passed --check"


# --------------------------------------------------------------------------- #
# 2. Every figure, re-derived from its source and compared to the committed text
# --------------------------------------------------------------------------- #


def test_the_judged_badge_matches_a_recompute_over_the_scorecards():
    shipped, roster, pooled_mean, pooled_n = _judged()
    committed = badge("judged")
    assert committed.message == f"{shipped}/{roster} SHIP {DOT} {pooled_mean:g}/120 {DOT} {_panel_size()}-model panel"
    assert committed.link == "docs/skill-judge-dashboard.md"
    assert str(pooled_n) in committed.alt, (
        "the alt text quotes the pooled n; a mean with no n is not a published statistic"
    )
    dashboard = (REPO_ROOT / "docs" / "skill-judge-dashboard.md").read_text(encoding="utf-8")
    assert f"{pooled_mean:g}" in dashboard, "the badge and the dashboard it links disagree about the pooled mean"
    provenance = (REPO_ROOT / "vendor" / "skill-judge" / "PROVENANCE.md").read_text(encoding="utf-8")
    assert "120 points" in provenance, "the badge's /120 denominator must come from the vendored rubric's own record"


def test_the_detector_f1_badge_matches_the_committed_f1_report():
    buckets = _f1_categories()
    published, below_floor, publish_none = (
        buckets["pass"],
        buckets["fail"],
        buckets["declared-and-uncovered"],
    )
    total = len(published) + len(below_floor) + len(publish_none)
    assert not below_floor, "a category now falls below the F1 floor; the badge must say so rather than reading clean"
    committed = badge("detector F1")
    assert committed.message == f"{_f1_published_score():.3f} {DOT} where a package can decide it"
    assert f"{len(published)} of {total}" in committed.alt, (
        f"the coverage count left the pill; the row must still publish it: {committed.alt!r}"
    )
    assert f"{len(publish_none)} publish none by rule" in committed.alt, (
        f"the count of categories that publish none left the row entirely: {committed.alt!r}"
    )
    assert committed.link == "docs/f1-report.md"
    for row in published:
        assert row["scenario_level"] and row["scenario_level"]["f1"] is not None, (
            f"{row['category']} is counted as publishing an F1 but has no scenario-level number"
        )


def test_the_output_eval_badge_matches_the_blind_control_arm():
    delta, with_rate, without_rate, n = _control_delta()
    committed = badge("output eval")
    assert committed.message == f"{with_rate:.2f} with {DOT} {without_rate:.2f} without"
    assert committed.link == "docs/skill-eval-report.md"
    assert str(n) in committed.alt, "the alt text quotes the control n"
    assert f"+{delta:.2f}" in committed.alt, (
        f"the measured delta left the pill; the row must still publish it: {committed.alt!r}"
    )


def test_the_output_eval_badge_is_the_control_arm_and_not_the_whole_corpus():
    """The whole-corpus arms are different, larger-n numbers. Publishing any of them
    under the words 'blind control' would badge a measurement nobody made.

    The row now shows two arms on the pill and the delta in the alt, so all three
    are checked against their whole-corpus look-alikes rather than the delta alone.
    """
    payload = json.loads(
        (REPO_ROOT / "eval" / "skill-eval-workspace" / "iteration-3" / "benchmark.json").read_text(encoding="utf-8")
    )
    summary = payload["run_summary"]
    corpus_delta = round(float(summary["delta"]["pass_rate"]), 2)
    corpus_with = round(float(summary["with_skill"]["pass_rate"]["mean"]), 2)
    corpus_without = round(float(summary["without_skill"]["pass_rate"]["mean"]), 2)
    control_delta, control_with, control_without, _n = _control_delta()
    committed = badge("output eval")
    assert f"{control_with:.2f} with" in committed.message
    assert f"{control_without:.2f} without" in committed.message
    assert f"+{control_delta:.2f}" in committed.alt
    if corpus_with != control_with:
        assert f"{corpus_with:.2f} with" not in committed.message, "the pill shows the whole-corpus with-arm"
    if corpus_without != control_without:
        assert f"{corpus_without:.2f} without" not in committed.message, "the pill shows the whole-corpus without-arm"
    if corpus_delta != control_delta:
        assert f"+{corpus_delta:.2f}" not in committed.alt, "the row quotes the whole-corpus delta as the control's"


def test_the_usf_badge_matches_the_validator_over_every_shipped_manifest():
    conformant, roster = _usf_conformant()
    committed = badge("USF v1.0")
    assert committed.message == f"{conformant}/{roster} skills {DOT} schema-validated"
    assert committed.link == "schemas/usf-v1.schema.json"
    assert (REPO_ROOT / "schemas" / "usf-v1.schema.json").is_file()


def test_the_usf_badge_names_the_version_the_manifests_declare():
    """`USF v1.0` is a claim about a specific revision of the format. The schema
    the badge links has to be that revision, or the label is decoration."""
    schema = json.loads((REPO_ROOT / "schemas" / "usf-v1.schema.json").read_text(encoding="utf-8"))
    assert "v1.0" in schema["title"], f"the badge says USF v1.0; the schema titles itself {schema['title']!r}"
    assert badge("USF v1.0").label == "USF v1.0"


def test_the_scenario_badge_matches_the_registry():
    registry = yaml.safe_load((REPO_ROOT / "scenarios" / "registry.yaml").read_text(encoding="utf-8"))
    scenarios = registry["scenarios"]
    assert registry["counts"]["total"] == len(scenarios), "registry counts.total disagrees with its own rows"
    committed = badge("scenarios")
    assert committed.message == f"{len(scenarios)} {DOT} tiered by decidability"
    assert committed.link == "scenarios/registry.yaml"
    tiers = {s["tier"] for s in scenarios}
    assert len(tiers) > 1, "the badge says 'tiered'; the registry must actually distinguish tiers"
    doctrine = registry["tier_doctrine"]
    assert tiers <= set(doctrine), (
        f"the badge says the tiers are a decidability axis; {sorted(tiers - set(doctrine))} has no tier_doctrine "
        "entry saying what it does or does not decide"
    )
    assert "decid" in " ".join(str(doctrine[tier]) for tier in sorted(tiers)).lower(), (
        "the badge claims the scenarios are tiered BY DECIDABILITY; the registry's own doctrine must say so"
    )


def test_the_licence_badge_matches_the_licence_file_and_both_manifests():
    text = (REPO_ROOT / "LICENSE").read_text(encoding="utf-8")
    assert "Apache License" in text and "Version 2.0" in text
    committed = badge("license")
    assert committed.message == "Apache-2.0"
    assert committed.link == "LICENSE"
    for manifest in (REPO_ROOT / "package.json", REPO_ROOT / ".claude-plugin" / "marketplace.json"):
        declared = json.loads(manifest.read_text(encoding="utf-8"))["license"]
        assert declared == committed.message, (
            f"{manifest.name} declares {declared!r}; the badge says {committed.message!r}"
        )


def test_the_rubric_badge_credits_the_vendored_upstream():
    """The rubric badge doubles as attribution for third-party work, so the slug
    it shows is read from the record of where the vendored bytes came from."""
    slug = _rubric_upstream()
    committed = badge("rubric")
    assert committed.message == slug
    assert committed.link == f"https://github.com/{slug}"
    assert (REPO_ROOT / "vendor" / "skill-judge" / "LICENSE").is_file(), "attribution without the licence beside it"
    assert slug in (REPO_ROOT / "THIRD_PARTY_LICENSES.md").read_text(encoding="utf-8")


# --------------------------------------------------------------------------- #
# 3. The F1 badge must not read as a shortfall
# --------------------------------------------------------------------------- #


def test_the_f1_badge_states_its_boundary_rather_than_implying_a_gap():
    """A bare `7 of 10` invites a reader to supply the missing, wrong explanation.

    Three categories publish no F1 BY RULE, and that is this repository's honesty
    apparatus, not a hole in it — so the pill states the SCOPE of the number it
    shows, the alt text carries the rule in full, and both link the page that
    spells it out. A ratio back on the pill is the failure this guards.
    """
    committed = badge("detector F1")
    assert "where a package can decide it" in committed.message, (
        f"the F1 badge reads {committed.message!r}; the boundary of the number must be stated on the pill"
    )
    assert not re.search(r"\d+\s+of\s+\d+", committed.message), (
        f"the F1 pill shows a ratio again ({committed.message!r}); it invites exactly the subtraction — "
        "and the wrong explanation of the remainder — that the wording exists to prevent"
    )
    assert "publish none by rule" in committed.alt, (
        f"the by-rule clause left the pill; the row must still carry the rule: {committed.alt!r}"
    )
    for loaded in ("fail", "missing", "gap", "incomplete", "uncovered", "no coverage", "todo", "partial"):
        assert loaded not in committed.message.lower(), (
            f"the F1 badge must not read as a shortfall: {committed.message!r}"
        )
    assert committed.link == "docs/f1-report.md"


def test_the_reason_the_f1_badge_gives_is_the_reason_the_report_gives():
    """The badge explains an absence. The explanation has to be the TRUE one.

    ``eval/f1-report.json``'s own rule is that **an empty static-detectable tier
    publishes no F1** — not that every scenario in those categories is
    out-of-artifact. ``AST05`` has an agent-judgable scenario and still publishes
    none. A badge whose stated reason is narrower than the rule is a badge that
    will be wrong the first time a category lands in the gap between them.
    """
    publish_none = _f1_categories()["declared-and-uncovered"]
    assert publish_none, "no category publishes none; this test and the badge clause are both stale"
    for row in publish_none:
        assert row["registry"]["static_detectable"] == [], (
            f"{row['category']} publishes no F1 but declares static-detectable scenarios "
            f"{row['registry']['static_detectable']} — the badge's stated rule no longer explains it"
        )
    alt = badge("detector F1").alt.lower()
    assert "static-detectable" in alt, (
        "the F1 badge's alt text must name the rule the report states (an empty static-detectable tier), "
        f"not a paraphrase that is false of at least one category: {badge('detector F1').alt!r}"
    )
    report = (REPO_ROOT / "docs" / "f1-report.md").read_text(encoding="utf-8")
    assert "publish no F1 at all" in report and "static-detectable tier is empty" in report, (
        "the page the badge links must state the rule the badge cites"
    )


def test_the_f1_badge_is_not_painted_as_a_caution_while_nothing_is_below_the_floor():
    """The clean state and the caveat state must be distinguishable. If they were
    the same colour the badge would carry no signal at all."""
    assert not _f1_categories()["fail"]
    assert badge("detector F1").colour == badge("judged").colour, (
        "with nothing below the floor, detector F1 is a measurement like the other two, not a warning"
    )


# --------------------------------------------------------------------------- #
# 4. Posture: the row cannot silently lose non-endorsement or the licence
# --------------------------------------------------------------------------- #


def test_the_row_leads_with_the_non_endorsement_notice():
    first = badges()[0]
    assert first.message == "NOT an OWASP project", (
        f"the row leads with {first.message!r}; a disclaimer that follows seven achievement badges reads as fine print"
    )
    assert first.link == "NOTICE"
    assert first.label == "", "the notice is a single solid pill so it is visually the odd one out"


def test_the_notice_the_badge_links_still_makes_the_claim_the_badge_makes():
    flat = " ".join((REPO_ROOT / "NOTICE").read_text(encoding="utf-8").split()).upper()
    assert "THIS REPOSITORY IS NOT AN OWASP PROJECT" in flat, (
        "NOTICE stopped saying this is not an OWASP project; the badge must not keep saying it alone"
    )


def test_no_badge_implies_this_is_an_owasp_project():
    """The repository NAME already misleads. The row must not compound it."""
    for item in badges():
        rendered = " ".join(item.fields + [item.alt]).lower()
        if "owasp" not in rendered:
            continue
        assert "not an owasp project" in rendered, f"a badge names OWASP without disclaiming it: {rendered!r}"
    assert "owasp.org" not in _badge_block(), "no badge may link the OWASP project page as if it were this project's"
    for word in ("official", "endorsed", "certified", "approved", "reference implementation"):
        assert word not in _badge_block().lower(), f"the row implies standing it does not have: {word!r}"


def test_the_row_carries_the_licence():
    """A licence badge is the one thing a reader looks for before cloning."""
    assert any(item.link == "LICENSE" for item in badges()), "the badge row dropped the licence"


@pytest.mark.parametrize("posture", ["NOT%20an%20OWASP%20project", "Apache--2.0"])
def test_the_posture_badges_cannot_be_removed_without_failing_the_check(tmp_path, posture):
    """Not just present — UNREMOVABLE. Delete either and regeneration puts it
    back, so a row that has quietly lost one cannot pass CI."""
    original = _readme()
    block = _badge_block(original)
    rendered = next(m.group(0) for m in BADGE_RE.finditer(block) if posture in m.group("img"))
    copy = tmp_path / "README.md"
    copy.write_text(original.replace(rendered, "", 1), encoding="utf-8")
    assert _run_check(copy).returncode == 1, f"a row missing {posture!r} passed --check"


# --------------------------------------------------------------------------- #
# 5. Scannability and provenance of the row as a whole
# --------------------------------------------------------------------------- #


def test_the_row_stays_scannable():
    """The stated goal is grasping the row QUICKLY. Past eight it is a wall."""
    count = len(badges())
    assert count <= 8, f"{count} badges is a wall, not a row"
    assert count >= 5, "a row this short is not carrying the three kinds of evidence the repo is different for"


def test_the_row_sits_immediately_under_the_h1():
    lines = _readme().splitlines()
    assert lines[0].startswith("# "), "README.md must open with its H1"
    assert lines[2] == BEGIN_MARKER, "the badge row must be the first thing under the H1, not buried below prose"


def test_the_row_carries_all_three_kinds_of_evidence():
    """Judged prose, detector accuracy, agent output. The third is the only one
    that measures whether a skill works at all, so a row missing any of the three
    is not showing what this repository is for."""
    links = {item.link for item in badges()}
    for evidence in ("docs/skill-judge-dashboard.md", "docs/f1-report.md", "docs/skill-eval-report.md"):
        assert evidence in links, f"the row does not link {evidence}"
        assert (REPO_ROOT / evidence).is_file()


def test_every_badge_links_something_that_substantiates_it():
    """Every link is either a path in this repository or the ONE off-repo URL the
    row is allowed: the upstream the vendored rubric is attributed to. Written as
    an allowlist rather than a denylist so no unrelated repository can be named
    here, in the row or in this file."""
    allowed_external = f"https://github.com/{_rubric_upstream()}"
    for item in badges():
        if item.link.startswith("http"):
            assert item.link == allowed_external, f"unexpected off-repo badge link: {item.link}"
            continue
        assert (REPO_ROOT / item.link).exists(), f"badge links {item.link}, which does not exist"


def test_every_number_the_row_shows_is_derived_from_something_in_this_repository():
    """No badge may carry a figure with no source.

    Every numeric token in every badge MESSAGE — the part a reader actually reads
    off the pill — is recomputed here from the artifact it came from. A number
    that appears in the row and in nothing else is, by definition, hand-typed.
    """
    shipped, roster, pooled_mean, _n = _judged()
    delta, with_rate, without_rate, _controls = _control_delta()
    conformant, usf_roster = _usf_conformant()
    registry = yaml.safe_load((REPO_ROOT / "scenarios" / "registry.yaml").read_text(encoding="utf-8"))
    buckets = _f1_categories()
    derived = {
        str(shipped),
        str(roster),
        f"{pooled_mean:g}",
        "120",  # the rubric's own scale, fixed by vendor/skill-judge/PROVENANCE.md
        str(_panel_size()),
        f"{_f1_published_score():.3f}",
        f"{delta:.2f}",
        f"{with_rate:.2f}",
        f"{without_rate:.2f}",
        str(conformant),
        str(usf_roster),
        str(len(registry["scenarios"])),
        str(len(buckets["pass"])),
        str(len(buckets["pass"]) + len(buckets["fail"]) + len(buckets["declared-and-uncovered"])),
        str(len(buckets["declared-and-uncovered"])),
        "2.0",  # the `2.0` of the SPDX identifier Apache-2.0, checked against LICENSE above
    }
    for item in badges():
        for token in re.findall(r"\d+(?:\.\d+)?", item.message):
            assert token in derived, f"badge {item.label or item.message!r} shows {token!r}, which nothing derives"


def test_no_badge_in_the_clean_state_is_coloured_as_a_success():
    """Green is a pass claim. Not one figure in this row is a pass claim — the
    repo's own F1 page calls a perfect score over its corpus 'nearly
    uninformative' — so no badge may be painted as one."""
    greens = {"4c1", "brightgreen", "green", "success", "97ca00", "0e8a16", "2ea44f"}
    for item in badges():
        assert item.colour.lower() not in greens, f"{item.label or item.message!r} is painted as a pass: {item.colour}"


def test_the_alt_text_of_every_badge_says_more_than_the_badge_does():
    """The alt text is what a screen reader and an image-blocked reader get. A
    badge whose alt merely repeats the pill has published nothing to them."""
    for item in badges():
        assert item.alt.strip(), f"badge {item.message!r} has no alt text"
        assert len(item.alt) > len(item.message), f"badge {item.message!r} alt adds nothing: {item.alt!r}"
