"""The manifests and the published anchor must agree — checked OFFLINE, in CI.

`scripts/sign_usf.py verify --identity did:web:jhkchan.github.io` is the check a human
runs: it fetches the DID document over HTTPS and confirms that the domain publishes the
key the manifests were signed with. That check is the one that means something, and it is
deliberately NOT what this file does.

WHY A COMMITTED COPY RATHER THAN A FETCH
----------------------------------------
A test that resolves `did:web` over the network fails when GitHub Pages has a bad minute,
and a pull request that goes red for a reason that has nothing to do with the pull request
teaches a maintainer to re-run CI without reading it — which is how a real failure gets
clicked past. So the anchor is checked against `config/did-web-anchor.json`, a byte-for-byte
copy of the document published at `https://jhkchan.github.io/.well-known/did.json`, and no
socket is opened. `test_the_check_above_opens_no_socket` proves the offline claim by making
every HTTP call raise while the whole check runs again.

WHAT THIS BUYS, AND WHAT IT DOES NOT
------------------------------------
Offline, the committed copy is an *expectation*, not evidence: it says which key this
repository believes the domain publishes. That is exactly the drift worth guarding — a
manifest re-signed with a different key, an identity edited by hand, a key rotated in one
place and not the other — and none of it needs the network to catch. What it cannot catch
is the domain publishing something else than this file records; only the live `verify
--identity` run does that, `test_the_committed_copy_names_the_url_a_human_must_refetch`
keeps the command and its URL in view, and the copy is refreshed by re-running `did-doc`.

And the ceiling above both: a `did:web` anchor is worth exactly as much as control of the
domain and its TLS. A verified signature answers *"who published this"*, never *"is this
safe"* — this repository's own AST01 rule, and the reason nothing here reads a valid
signature as a clean bill of health.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from scripts.sign_usf import (
    DidResolutionError,
    assertion_keys,
    did_document,
    parse_did_web,
    public_key_multibase,
)
from validators.usf import (
    SIGNATURE_STATE_SIGNED,
    load_manifest,
    signature_state,
    verify_signature,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
SKILLS_DIR = REPO_ROOT / "skills"

#: The offline copy of the published DID document. Regenerated, never hand-edited:
#:     python3 scripts/sign_usf.py did-doc --identity did:web:jhkchan.github.io \
#:         --public-key ed25519:<64 hex> --output config/did-web-anchor.json
ANCHOR_PATH = REPO_ROOT / "config" / "did-web-anchor.json"

#: The identity the manifests claim. Written out here so that editing the anchor file and
#: editing the manifests to match still fails: both are compared against a third value.
EXPECTED_IDENTITY = "did:web:jhkchan.github.io"

#: The key `EXPECTED_IDENTITY` publishes, in the `publicKeyMultibase` form the DID document
#: carries. Pinned so a rotation is a deliberate edit to this line, with a test run that
#: says which manifests moved with it, rather than a silent agreement between two files
#: that were both regenerated by the same command.
EXPECTED_MULTIBASE = "z6MknXd1uE3trJDoC72ZJXtQ72z5EiCSucLLrLr1KS3seVwK"

MANIFEST_PATHS = sorted(SKILLS_DIR.glob("*/skill.usf.yaml"))


def _anchor_document() -> dict:
    return json.loads(ANCHOR_PATH.read_text(encoding="utf-8"))


def _published_keys() -> list:
    """The `assertionMethod` keys the committed copy publishes, parsed by the resolver.

    Parsed with `sign_usf.assertion_keys`, the same function the network path uses, so the
    offline check cannot accept a document the online one would reject.
    """
    return assertion_keys(_anchor_document(), parse_did_web(EXPECTED_IDENTITY))


# --------------------------------------------------------------------------- #
# The committed copy is the document the tool would publish
# --------------------------------------------------------------------------- #


def test_the_committed_anchor_is_the_document_did_doc_emits():
    """A hand-edited anchor file is a forged expectation; this is what catches one."""
    document = _anchor_document()
    assert document["id"] == EXPECTED_IDENTITY

    key = _published_keys()[0]
    regenerated = did_document(parse_did_web(EXPECTED_IDENTITY), key.public_key.split(":", 1)[1])
    assert document == regenerated, (
        "config/did-web-anchor.json is not what `sign_usf.py did-doc` emits for the key it "
        "carries. Regenerate it rather than editing it."
    )


def test_the_anchor_publishes_exactly_one_assertion_key_and_it_is_the_pinned_one():
    keys = _published_keys()
    assert len(keys) == 1, f"the anchor publishes {len(keys)} assertion keys; a rotation overlap is a deliberate state"
    assert keys[0].multibase == EXPECTED_MULTIBASE
    assert keys[0].method_id == f"{EXPECTED_IDENTITY}#{EXPECTED_MULTIBASE}"
    # The multibase and the hex form are two spellings of one key; a copy that lost the
    # multicodec prefix or the 'z' would decode to a different key without looking wrong.
    assert public_key_multibase(bytes.fromhex(keys[0].public_key.split(":", 1)[1])) == EXPECTED_MULTIBASE


# --------------------------------------------------------------------------- #
# Every manifest agrees with it
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize("path", MANIFEST_PATHS, ids=[p.parent.name for p in MANIFEST_PATHS])
def test_every_manifest_anchors_to_the_published_key(path):
    """identity, signing_key and signature, each checked against the anchor and not
    against the manifest's own claim about itself."""
    published = _published_keys()
    manifest = load_manifest(path)
    author = manifest.get("author") or {}

    assert signature_state(manifest) == SIGNATURE_STATE_SIGNED
    assert author.get("identity") == EXPECTED_IDENTITY, (
        f"{path.parent.name} claims identity {author.get('identity')!r}; the anchor is {EXPECTED_IDENTITY}"
    )

    match = next((key for key in published if key.public_key == author.get("signing_key")), None)
    assert match is not None, (
        f"{path.parent.name} is signed with {author.get('signing_key')!r}, which {EXPECTED_IDENTITY} does not publish"
    )

    # Against the key the ANCHOR publishes, not the one the file carries. Passing the
    # manifest's own key back to the verifier proves only internal consistency.
    assert verify_signature(manifest, public_key_hex=match.public_key) is True


def test_the_eleven_are_one_publisher_and_one_key():
    """Eleven manifests that each verify against a different key would pass the per-file
    check above and still mean this package has no single publisher."""
    identities = set()
    keys = set()
    for path in MANIFEST_PATHS:
        author = load_manifest(path).get("author") or {}
        identities.add(author.get("identity"))
        keys.add(author.get("signing_key"))
    assert identities == {EXPECTED_IDENTITY}, sorted(identities, key=str)
    assert len(keys) == 1, sorted(keys, key=str)
    assert keys == {_published_keys()[0].public_key}


def test_the_roster_this_file_checks_is_the_whole_roster():
    """A glob that quietly matched nothing would make every case above vacuous."""
    on_disk = sorted(p.name for p in SKILLS_DIR.iterdir() if p.is_dir())
    assert [p.parent.name for p in MANIFEST_PATHS] == on_disk
    assert len(MANIFEST_PATHS) == 11


# --------------------------------------------------------------------------- #
# The offline claim, and the negative controls
# --------------------------------------------------------------------------- #


def test_the_check_above_opens_no_socket(monkeypatch):
    """CI must never fail here because a domain was briefly unreachable."""

    def refuse(*args, **kwargs):
        raise AssertionError("this check reached for the network; it must read the committed copy")

    monkeypatch.setattr("scripts.sign_usf._http_get", refuse)
    monkeypatch.setattr("urllib.request.urlopen", refuse)

    published = _published_keys()
    for path in MANIFEST_PATHS:
        manifest = load_manifest(path)
        assert verify_signature(manifest, public_key_hex=published[0].public_key) is True


def test_an_anchor_that_publishes_a_different_key_does_not_satisfy_the_manifests():
    """The case the whole file exists for: a key rotated in one place and not the other."""
    other = "11" * 32
    document = did_document(parse_did_web(EXPECTED_IDENTITY), other)
    key = assertion_keys(document, parse_did_web(EXPECTED_IDENTITY))[0]

    manifest = load_manifest(MANIFEST_PATHS[0])
    assert key.public_key != (manifest.get("author") or {}).get("signing_key")
    assert verify_signature(manifest, public_key_hex=key.public_key) is False


def test_a_key_published_only_for_authentication_is_not_accepted_offline():
    """Same rule as the network path: a manifest signature is an assertion, and a key
    published under any other relationship anchors nothing here."""
    document = _anchor_document()
    document.pop("assertionMethod")
    with pytest.raises(DidResolutionError, match="assertionMethod"):
        assertion_keys(document, parse_did_web(EXPECTED_IDENTITY))


def test_an_anchor_document_for_another_identifier_anchors_nothing():
    document = _anchor_document()
    document["id"] = "did:web:evil.example"
    with pytest.raises(DidResolutionError, match="does not claim the identifier"):
        assertion_keys(document, parse_did_web(EXPECTED_IDENTITY))


def test_the_committed_copy_names_the_url_a_human_must_refetch():
    """Offline agreement is not proof the domain still publishes this. The command that
    checks that is `verify --identity`, and this keeps its URL in the file's own terms."""
    did = parse_did_web(EXPECTED_IDENTITY)
    assert did.url == "https://jhkchan.github.io/.well-known/did.json"
    assert did.url in (REPO_ROOT / "docs" / "signing.md").read_text(encoding="utf-8")
