#!/usr/bin/env python3
"""scripts/external_validation.py — the external-corpus audit, recorded and drift-guarded.

Every other published figure in this repository is generated from the artifact
that produced it and ``--check``-guarded, because a hand-typed figure is a stale
figure and this repository has been bitten by that four times. The external
validation in ``docs/external-validation.md`` is no different, with one
constraint the others do not have: **its sources are not in the repository and
cannot be in CI.**

The corpus is 360 third-party skill packages living in eight checkouts on a
maintainer's disk. They cannot be vendored (licence, size, and the point is that
they are other people's work), and re-running the audit needs all eight present.
So the guard is one step removed, exactly as the task's own fallback allows:

* ``eval/external-validation.json`` is the committed, machine-readable record of
  a run — per-check firing counts before and after the fixes, corpus sizes, the
  fixture-versus-wild declaration census, and one adjudication row per firing
  that was not one of the three universal ones.
* ``--check`` fails if ``docs/external-validation.md``'s generated regions and
  that record part company. That is the same contract
  ``scripts/generate_badges.py`` holds over the README badge row.
* ``tests/test_external_validation.py`` then does the part ``--check`` cannot: it
  re-derives, from the SHIPPED DETECTORS, everything about the record that is
  derivable without the corpus — the 36-check roster, every check's category,
  its ``covers`` ruling, its registry ids, its tier — and fails if the record
  describes a detector suite this repository no longer has. A check added,
  removed, renamed or reclassified breaks the build rather than quietly
  invalidating a published table.

What that guard CANNOT catch is a firing count going stale because a detector's
*logic* changed while its identity did not. Nothing short of re-running over the
corpus can catch that, so the record carries the tree it was measured against and
the report says on its face that the counts are a dated measurement rather than a
live one. Re-record with ``--audit`` + ``--record`` whenever a detector's
behaviour changes.

Three modes, in the order a re-run uses them::

    # 1. run the shipped audit over a pinned corpus (needs the corpora on disk)
    python3 scripts/external_validation.py --audit corpus.json --out after.json

    # 2. fold a before-tree dump and an after-tree dump into the record
    python3 scripts/external_validation.py --record --before before.json \\
        --after after.json --before-tree <sha> --after-tree <sha> --date <YYYY-MM-DD>

    # 3. rewrite (or verify) the generated regions of the report
    python3 scripts/external_validation.py
    python3 scripts/external_validation.py --check

``corpus.json`` is a list of ``{"label": "A".."D", "path": "/abs/path/to/pkg"}``
and is deliberately NOT committed: it holds local absolute paths, and naming the
checkouts is what the record exists to avoid. Corpora are identified in every
committed artifact by an opaque label plus a description of their shape and
provenance. The one exception is corpus A, whose upstream this repository already
cites by name as the vendored rubric's origin.
"""

from __future__ import annotations

import argparse
import collections
import importlib.util
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:  # allow `python3 scripts/external_validation.py`
    sys.path.insert(0, str(REPO_ROOT))

RECORD = REPO_ROOT / "eval" / "external-validation.json"
REPORT = REPO_ROOT / "docs" / "external-validation.md"

#: Marker pairs delimiting each generated region of the report. The prose around
#: them is hand-written and untouched; only what a number lives in is generated.
REGIONS = ("corpora", "declarations", "checks", "adjudications", "totals")


class ExternalValidationError(RuntimeError):
    """The record and the repository disagree, or the report has lost a marker."""


def begin(region: str) -> str:
    return f"<!-- BEGIN:{region} — generated by scripts/external_validation.py; do not hand-edit -->"


def end(region: str) -> str:
    return f"<!-- END:{region} -->"


# ---------------------------------------------------------------------------
# Mode 1 — run the shipped audit over a pinned corpus
# ---------------------------------------------------------------------------


def load_bridge(tree: Path):
    """Import ``cli/lib/bridge.py`` from an arbitrary checkout of this repository.

    Taking the tree as an argument is what makes a before/after measurement
    possible at all: the "before" run is this same function pointed at a
    ``git archive`` of the pre-fix commit, so both halves of the comparison go
    through the same harness and only the detector logic differs.
    """
    path = tree / "cli" / "lib" / "bridge.py"
    if not path.is_file():
        raise ExternalValidationError(f"no bridge at {path}")
    spec = importlib.util.spec_from_file_location("ast10_external_validation_bridge", path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    sys.path.insert(0, str(tree))
    spec.loader.exec_module(module)
    return module


def run_audit(corpus: list[dict], tree: Path) -> list[dict]:
    """One raw audit dump: every firing, per package, with the evidence string."""
    bridge = load_bridge(tree)
    records = []
    for row in corpus:
        result = bridge.audit(row["path"])
        # `declaration_state` answers "is there a permissions block"; the report
        # also needs the narrower "is there a `network` key", because that is the
        # exact key `AST01-undeclared-egress` diffs a destination against. Read
        # through the same adapter the audit used so the two agree by
        # construction rather than by inference from the coarser boolean.
        adapted, _notes = bridge.adapt_manifest(bridge.read_manifest(Path(row["path"]))[0])
        permissions = (adapted or {}).get("permissions") or {}
        fired = [
            {
                "category": category["category"],
                "check": finding["scenario"],
                # The pre-fix bridge did not carry `covers` in the payload; the
                # record takes every check's ruling from the shipped modules
                # instead, so a missing key here is expected and not an error.
                "covers": finding.get("covers"),
                "evidence": finding.get("evidence", ""),
            }
            for category in result["categories"]
            for finding in category.get("findings", [])
            if finding["detected"]
        ]
        declaration = result.get("declaration") or {}
        records.append(
            {
                "label": row["label"],
                "checks_run": result["totals"]["checks_run"],
                "manifest_found": bool(declaration.get("manifest_found")),
                "declares_permissions": bool(declaration.get("declares_permissions")),
                "declares_network": "network" in permissions,
                "declares_content_hash": bool(declaration.get("declares_content_hash")),
                "usf_manifest_file": (Path(row["path"]) / "skill.usf.yaml").is_file(),
                "fired": fired,
            }
        )
    return records


# ---------------------------------------------------------------------------
# Mode 2 — fold two dumps into the committed record
# ---------------------------------------------------------------------------


def shipped_checks() -> list[dict]:
    """The 36-check roster, read from the detectors this repository ships today.

    Also the anchor ``tests/test_external_validation.py`` re-derives against, so
    it deliberately reads the modules rather than the record.
    """
    bridge = load_bridge(REPO_ROOT)
    roster = []
    for category in bridge.CATEGORIES:
        module = bridge.load_detector(category)
        claims = bridge.check_claims(module)
        tiers = bridge.check_tiers(module)
        for name in getattr(module, "DETECTORS", {}):
            roster.append(
                {
                    "category": category,
                    "check": name,
                    "covers": claims.get(name, {}).get("covers"),
                    "registry_ids": list(claims.get(name, {}).get("registry_ids", [])),
                    "tier": tiers.get(name),
                }
            )
    return roster


def fixture_census() -> dict:
    """How many labeled fixture cases declare what the wild does not.

    The headline of the whole report is a comparison between this census and the
    same census over the 360 real packages, so it is measured rather than
    asserted -- from ``detectors/fixture_loader.py``, the same loader the F1
    report scores through.
    """
    from detectors import fixture_loader  # noqa: PLC0415  (needs the sys.path fix-up above)

    per_category: dict[str, dict] = {}
    for directory in sorted((REPO_ROOT / "fixtures").glob("AST*")):
        cases = fixture_loader.load_category_cases(directory.name)
        counts = {
            "cases": 0,
            "declares_permissions": 0,
            "declares_network": 0,
            "declares_content_hash": 0,
            "usf_manifest_file": 0,
        }
        for case in cases:
            manifest = (case.pkg or {}).get("manifest") or {}
            permissions = manifest.get("permissions") or {}
            counts["cases"] += 1
            counts["declares_permissions"] += bool(permissions)
            counts["declares_network"] += "network" in permissions
            counts["declares_content_hash"] += bool(manifest.get("content_hash"))
            # `case.path` is the case's SKILL.md, not its directory.
            counts["usf_manifest_file"] += (REPO_ROOT / case.path).parent.joinpath("skill.usf.yaml").is_file()
        per_category[directory.name] = counts
    total = {key: sum(c[key] for c in per_category.values()) for key in next(iter(per_category.values()))}
    return {"per_category": per_category, "total": total}


def tally(dump: list[dict]) -> collections.Counter:
    counter: collections.Counter = collections.Counter()
    for record in dump:
        for firing in record["fired"]:
            counter[firing["check"]] += 1
    return counter


def build_record(before: list[dict], after: list[dict], run: dict) -> dict:
    """Fold the two dumps and the live detector roster into the committed record."""
    if len(before) != len(after):
        raise ExternalValidationError(f"dumps disagree on corpus size: {len(before)} vs {len(after)}")
    before_counts, after_counts = tally(before), tally(after)
    roster = shipped_checks()
    known = {row["check"] for row in roster}
    unknown = (set(before_counts) | set(after_counts)) - known
    if unknown:
        raise ExternalValidationError(f"the dumps contain checks this tree does not ship: {sorted(unknown)}")

    checks = [
        dict(row, before=before_counts.get(row["check"], 0), after=after_counts.get(row["check"], 0)) for row in roster
    ]
    by_label: collections.Counter = collections.Counter(r["label"] for r in after)
    wild = {
        "packages": len(after),
        "manifest_readable": sum(1 for r in after if r["manifest_found"]),
        "declares_permissions": sum(1 for r in after if r["declares_permissions"]),
        "declares_network": sum(1 for r in after if r.get("declares_network")),
        "declares_content_hash": sum(1 for r in after if r["declares_content_hash"]),
        "usf_manifest_file": sum(1 for r in after if r["usf_manifest_file"]),
    }
    checks_per_package = sorted({r["checks_run"] for r in after})
    if len(checks_per_package) != 1:
        raise ExternalValidationError(f"packages saw different check counts: {checks_per_package}")

    # `corpora`, `corpus_hygiene` and `adjudications` are hand-curated: a corpus
    # description and a verdict on a firing are judgements, not measurements, and
    # re-recording must carry them forward rather than blank them. The tests hold
    # them consistent with the measured half.
    existing = json.loads(RECORD.read_text(encoding="utf-8")) if RECORD.is_file() else {}
    return {
        "generated_by": "scripts/external_validation.py --record",
        "run": run,
        "corpora": existing.get("corpora", []),
        "corpus_hygiene": existing.get("corpus_hygiene", {}),
        "totals": {
            "packages": len(after),
            "checks_per_package": checks_per_package[0],
            "check_runs": checks_per_package[0] * len(after),
            "packages_by_label": dict(sorted(by_label.items())),
            "firings_before": sum(before_counts.values()),
            "firings_after": sum(after_counts.values()),
        },
        "wild_declarations": wild,
        "fixture_declarations": fixture_census(),
        "checks": checks,
        "adjudications": existing.get("adjudications", []),
    }


# ---------------------------------------------------------------------------
# Mode 3 — render the generated regions of the report
# ---------------------------------------------------------------------------


def _table(headers: list[str], rows: list[list[str]]) -> str:
    return "\n".join(
        ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
        + ["| " + " | ".join(row) + " |" for row in rows]
    )


def render_corpora(record: dict) -> str:
    rows = [
        [
            c["label"],
            str(c["packages"]),
            c["independence"],
            c["shape"],
        ]
        for c in record["corpora"]
    ]
    rows.append(["**total**", f"**{record['totals']['packages']}**", "", ""])
    return _table(["corpus", "packages", "authored by", "what it is"], rows)


def render_declarations(record: dict) -> str:
    fixtures = record["fixture_declarations"]["total"]
    wild = record["wild_declarations"]

    def pct(n: int, d: int) -> str:
        return f"{n}/{d} ({100 * n / d:.0f}%)" if d else "0/0"

    rows = [
        [
            "declares a `permissions` block",
            pct(fixtures["declares_permissions"], fixtures["cases"]),
            pct(wild["declares_permissions"], wild["packages"]),
        ],
        [
            "declares `permissions.network`",
            pct(fixtures["declares_network"], fixtures["cases"]),
            pct(wild["declares_network"], wild["packages"]),
        ],
        [
            "declares a `content_hash`",
            pct(fixtures["declares_content_hash"], fixtures["cases"]),
            pct(wild["declares_content_hash"], wild["packages"]),
        ],
        [
            "ships a `skill.usf.yaml`",
            pct(fixtures["usf_manifest_file"], fixtures["cases"]),
            pct(wild["usf_manifest_file"], wild["packages"]),
        ],
    ]
    per = record["fixture_declarations"]["per_category"]
    detail = _table(
        ["category", "labeled cases", "declare `permissions`", "declare `permissions.network`"],
        [
            [cat, str(c["cases"]), str(c["declares_permissions"]), str(c["declares_network"])]
            for cat, c in sorted(per.items())
        ],
    )
    return (
        _table(["", "labeled fixture cases", "real packages audited"], rows)
        + "\n\nPer category, in the corpus every published F1 is measured over:\n\n"
        + detail
    )


def render_checks(record: dict) -> str:
    rows = []
    for check in record["checks"]:
        delta = check["after"] - check["before"]
        rows.append(
            [
                check["category"],
                f"`{check['check']}`",
                check["covers"],
                str(check["before"]),
                str(check["after"]),
                "—" if delta == 0 else f"{delta:+d}",
            ]
        )
    totals = record["totals"]
    rows.append(
        [
            "",
            "**all checks**",
            "",
            f"**{totals['firings_before']:,}**",
            f"**{totals['firings_after']:,}**",
            f"**{totals['firings_after'] - totals['firings_before']:+d}**",
        ]
    )
    return _table(["cat", "check", "covers", "fired before", "fired after", "Δ"], rows)


def render_adjudications(record: dict) -> str:
    rows = [
        [
            f"`{a['check']}`",
            a["covers"],
            a["corpus"],
            str(a["before"]),
            str(a["after"]),
            a["verdict"],
            a["what"],
        ]
        for a in record["adjudications"]
    ]
    return _table(["check", "covers", "corpus", "before", "after", "verdict", "what it was"], rows)


def render_totals(record: dict) -> str:
    """The arithmetic, every figure of it derived from the record's own rows.

    Nothing here is a constant. "The three universal checks" is a count of the
    checks that actually fired on every package, not the number three; the
    false-positive rate divides adjudicated false firings by covering-check runs.
    A future re-record that changes any of those changes this table, which is the
    point of generating it.
    """
    totals = record["totals"]
    checks = record["checks"]
    packages = totals["packages"]
    covering = [c for c in checks if c["covers"] == "full"]
    universal = [c for c in checks if c["before"] == packages and c["after"] == packages]
    covering_runs = len(covering) * packages
    false_before = sum(a["before"] for a in record["adjudications"] if _is_false_positive(a))
    false_after = sum(a["after"] for a in record["adjudications"] if _is_false_positive(a))
    rows = [
        ["packages audited", f"{packages:,}"],
        ["checks run per package", str(totals["checks_per_package"])],
        ["individual check runs", f"{totals['check_runs']:,}"],
        ["checks that decide a named scenario (`covers: full`)", str(len(covering))],
        ["covering-check runs", f"{covering_runs:,}"],
        [
            "checks that fired on every package",
            f"{len(universal)} ({', '.join('`' + c['check'] + '`' for c in universal)})",
        ],
        ["total firings, before → after", f"{totals['firings_before']:,} → {totals['firings_after']:,}"],
        [
            "of those, the universal checks",
            f"{sum(c['before'] for c in universal):,} → {sum(c['after'] for c in universal):,}",
        ],
        [
            "covering-check firings, before → after",
            f"{sum(c['before'] for c in covering)} → {sum(c['after'] for c in covering)}",
        ],
        ["of those, adjudicated FALSE, before → after", f"{false_before} → {false_after}"],
        [
            "false-positive rate over covering-check runs, after",
            f"{false_after}/{covering_runs:,} = {100 * false_after / covering_runs:.3f}%",
        ],
    ]
    return _table(["measure", "value"], rows)


def _is_false_positive(adjudication: dict) -> bool:
    """Only a `covers: full` firing can be a false positive in the sense that matters.

    A `category-precondition` or `artifact-signal-only` firing convicts nothing,
    so calling it a false positive would import a claim the check never made --
    the exact confusion the audit renderer's vocabulary exists to prevent.
    """
    return adjudication["covers"] == "full" and adjudication["verdict"].startswith("false positive")


RENDERERS = {
    "corpora": render_corpora,
    "declarations": render_declarations,
    "checks": render_checks,
    "adjudications": render_adjudications,
    "totals": render_totals,
}


def rewrite(text: str, record: dict) -> str:
    """Replace every marked region of ``text``, touching nothing else."""
    for region in REGIONS:
        start, stop = text.find(begin(region)), text.find(end(region))
        if start == -1 or stop == -1 or stop < start:
            raise ExternalValidationError(
                f"{REPORT.name} is missing the {begin(region)} / {end(region)} markers "
                "— refusing to guess where the block belongs"
            )
        block = RENDERERS[region](record)
        text = text[: start + len(begin(region))] + "\n\n" + block + "\n\n" + text[stop:]
    return text


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="scripts/external_validation.py",
        description="Record and drift-guard the external-corpus audit published in docs/external-validation.md.",
    )
    parser.add_argument("--check", action="store_true", help="exit 1 if the report is out of date; write nothing")
    parser.add_argument("--audit", metavar="CORPUS", help="run the shipped audit over a pinned corpus manifest")
    parser.add_argument("--tree", default=str(REPO_ROOT), help="repository checkout to audit with (default: this one)")
    parser.add_argument("--out", help="where --audit writes its raw dump")
    parser.add_argument("--record", action="store_true", help="fold two raw dumps into eval/external-validation.json")
    parser.add_argument("--before", help="--record: the pre-fix raw dump")
    parser.add_argument("--after", help="--record: the post-fix raw dump")
    parser.add_argument("--before-tree", default="", help="--record: identifier of the tree --before was measured on")
    parser.add_argument("--after-tree", default="", help="--record: identifier of the tree --after was measured on")
    parser.add_argument("--date", default="", help="--record: the date of the run")
    args = parser.parse_args(argv)

    if args.audit:
        if not args.out:
            parser.error("--audit needs --out")
        corpus = json.loads(Path(args.audit).read_text(encoding="utf-8"))
        dump = run_audit(corpus, Path(args.tree).resolve())
        Path(args.out).write_text(json.dumps(dump, indent=1), encoding="utf-8")
        print(f"{args.out}: {len(dump)} package(s) audited with {args.tree}")
        return 0

    if args.record:
        if not (args.before and args.after):
            parser.error("--record needs --before and --after")
        record = build_record(
            json.loads(Path(args.before).read_text(encoding="utf-8")),
            json.loads(Path(args.after).read_text(encoding="utf-8")),
            {"date": args.date, "before_tree": args.before_tree, "after_tree": args.after_tree},
        )
        RECORD.write_text(json.dumps(record, indent=1) + "\n", encoding="utf-8")
        print(f"{RECORD}: recorded {record['totals']['packages']} package(s)")
        return 0

    record = json.loads(RECORD.read_text(encoding="utf-8"))
    current = REPORT.read_text(encoding="utf-8")
    updated = rewrite(current, record)

    if args.check:
        if updated != current:
            print(f"{REPORT}: generated regions are out of date — run scripts/external_validation.py")
            return 1
        print(f"{REPORT}: up to date ({record['totals']['packages']} package(s) recorded)")
        return 0

    if updated != current:
        REPORT.write_text(updated, encoding="utf-8")
        print(f"{REPORT}: generated regions rewritten")
    else:
        print(f"{REPORT}: generated regions unchanged")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
